# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

module Pangea
  module Resources
    module Tailscale
      include TailscaleAcl
      include TailscaleAwsExternalId
      include TailscaleContacts
      include TailscaleDeviceAuthorization
      include TailscaleDeviceKey
      include TailscaleDeviceSubnetRoutes
      include TailscaleDeviceTags
      include TailscaleDnsConfiguration
      include TailscaleDnsNameservers
      include TailscaleDnsPreferences
      include TailscaleDnsSearchPaths
      include TailscaleDnsSplitNameservers
      include TailscaleFederatedIdentity
      include TailscaleLogstreamConfiguration
      include TailscaleOauthClient
      include TailscalePostureIntegration
      include TailscaleTailnetKey
      include TailscaleTailnetSettings
      include TailscaleWebhook
    end
  end
end
