# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_device_authorization/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDeviceAuthorization
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_device_authorization,
      attributes_class: Tailscale::Types::DeviceAuthorizationAttributes,
          outputs: { id: :id },
          map: [:device_id, :authorized]
  end
  module Tailscale
    include TailscaleDeviceAuthorization
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
