# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class DeviceAuthorizationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :device_id, T::String
    attribute :authorized, T::Bool
  end
end
