# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_posture_integration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscalePostureIntegration
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_posture_integration,
      attributes_class: Tailscale::Types::PostureIntegrationAttributes,
          outputs: { id: :id },
          map: [:posture_provider, :client_secret],
          map_present: [:client_id, :cloud_id, :tenant_id]
  end
  module Tailscale
    include TailscalePostureIntegration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
