# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class PostureIntegrationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :posture_provider, T::String
    attribute :client_secret, T::String
    attribute? :client_id, T::String.optional
    attribute? :cloud_id, T::String.optional
    attribute? :tenant_id, T::String.optional
  end
end
