# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_dns_split_nameservers/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDnsSplitNameservers
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_dns_split_nameservers,
      attributes_class: Tailscale::Types::DnsSplitNameserversAttributes,
          outputs: { id: :id },
          map: [:domain, :nameservers]
  end
  module Tailscale
    include TailscaleDnsSplitNameservers
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
