# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class DnsSplitNameserversAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :domain, T::String
    attribute :nameservers, T::Array.of(T::String)
  end
end
