# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_acl/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleAcl
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_acl,
      attributes_class: Tailscale::Types::AclAttributes,
          outputs: { id: :id },
          map: [:acl],
          map_present: [:overwrite_existing_content, :reset_acl_on_destroy]
  end
  module Tailscale
    include TailscaleAcl
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
