# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class AclAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :acl, T::String
    attribute? :overwrite_existing_content, T::Bool.optional
    attribute? :reset_acl_on_destroy, T::Bool.optional
  end
end
