# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_contacts/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleContacts
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_contacts,
      attributes_class: Tailscale::Types::ContactsAttributes,
          outputs: { id: :id },
          map: [:account, :support, :security]
  end
  module Tailscale
    include TailscaleContacts
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
