# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class ContactsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :account, T::String
    attribute :support, T::String
    attribute :security, T::String
  end
end
