# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_dns_preferences/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDnsPreferences
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_dns_preferences,
      attributes_class: Tailscale::Types::DnsPreferencesAttributes,
          outputs: { id: :id },
          map: [:magic_dns]
  end
  module Tailscale
    include TailscaleDnsPreferences
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
