# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_tailnet_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleTailnetKey
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_tailnet_key,
      attributes_class: Tailscale::Types::TailnetKeyAttributes,
          outputs: { id: :id, user_id: :user_id, key: :key, created_at: :created_at, expires_at: :expires_at, invalid: :invalid },
          map_present: [:reusable, :ephemeral, :preauthorized, :expiry, :description, :tags, :recreate_if_invalid]
  end
  module Tailscale
    include TailscaleTailnetKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
