# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class TailnetKeyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute? :reusable, T::Bool.optional
    attribute? :ephemeral, T::Bool.optional
    attribute? :preauthorized, T::Bool.optional
    attribute? :expiry, T::Integer.optional
    attribute? :description, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :recreate_if_invalid, T::String.optional
  end
end
