# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_dns_nameservers/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDnsNameservers
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_dns_nameservers,
      attributes_class: Tailscale::Types::DnsNameserversAttributes,
          outputs: { id: :id },
          map: [:nameservers]
  end
  module Tailscale
    include TailscaleDnsNameservers
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
