# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_federated_identity/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleFederatedIdentity
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_federated_identity,
      attributes_class: Tailscale::Types::FederatedIdentityAttributes,
          outputs: { id: :id, created_at: :created_at, updated_at: :updated_at, user_id: :user_id },
          map: [:issuer, :subject, :scopes],
          map_present: [:audience, :tags, :description, :custom_claim_rules]
  end
  module Tailscale
    include TailscaleFederatedIdentity
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
