# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class FederatedIdentityAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :issuer, T::String
    attribute :subject, T::String
    attribute :scopes, T::Array.of(T::String)
    attribute? :audience, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
    attribute? :custom_claim_rules, T::Hash.optional
  end
end
