# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_device_tags/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDeviceTags
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_device_tags,
      attributes_class: Tailscale::Types::DeviceTagsAttributes,
          outputs: { id: :id },
          map: [:device_id, :tags]
  end
  module Tailscale
    include TailscaleDeviceTags
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
