# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_oauth_client/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleOauthClient
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_oauth_client,
      attributes_class: Tailscale::Types::OauthClientAttributes,
          outputs: { id: :id, key: :key, created_at: :created_at, updated_at: :updated_at, user_id: :user_id },
          map: [:scopes],
          map_present: [:description, :tags]
  end
  module Tailscale
    include TailscaleOauthClient
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
