# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class OauthClientAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :scopes, T::Array.of(T::String)
    attribute? :description, T::String.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
