# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

module Pangea; module Resources; module Tailscale; module Types; end; end; end; end

# Tailscale resources
require_relative 'pangea/resources/tailscale_acl/resource'
require_relative 'pangea/resources/tailscale_aws_external_id/resource'
require_relative 'pangea/resources/tailscale_contacts/resource'
require_relative 'pangea/resources/tailscale_device_authorization/resource'
require_relative 'pangea/resources/tailscale_device_key/resource'
require_relative 'pangea/resources/tailscale_device_subnet_routes/resource'
require_relative 'pangea/resources/tailscale_device_tags/resource'
require_relative 'pangea/resources/tailscale_dns_configuration/resource'
require_relative 'pangea/resources/tailscale_dns_nameservers/resource'
require_relative 'pangea/resources/tailscale_dns_preferences/resource'
require_relative 'pangea/resources/tailscale_dns_search_paths/resource'
require_relative 'pangea/resources/tailscale_dns_split_nameservers/resource'
require_relative 'pangea/resources/tailscale_federated_identity/resource'
require_relative 'pangea/resources/tailscale_logstream_configuration/resource'
require_relative 'pangea/resources/tailscale_oauth_client/resource'
require_relative 'pangea/resources/tailscale_posture_integration/resource'
require_relative 'pangea/resources/tailscale_tailnet_key/resource'
require_relative 'pangea/resources/tailscale_tailnet_settings/resource'
require_relative 'pangea/resources/tailscale_webhook/resource'

# Tailscale module aggregator
require_relative 'pangea/resources/tailscale'
