# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_dns_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDnsConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_dns_configuration,
      attributes_class: Tailscale::Types::DnsConfigurationAttributes,
          outputs: { id: :id },
          map_present: [:magic_dns, :override_local_dns, :search_paths, :nameservers, :split_dns]
  end
  module Tailscale
    include TailscaleDnsConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
