# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class DnsConfigurationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute? :magic_dns, T::Bool.optional
    attribute? :override_local_dns, T::Bool.optional
    attribute? :search_paths, T::Array.of(T::String).optional
    attribute? :nameservers, T::String.optional
    attribute? :split_dns, T::String.optional
  end
end
