# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_webhook/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleWebhook
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_webhook,
      attributes_class: Tailscale::Types::WebhookAttributes,
          outputs: { id: :id, secret: :secret },
          map: [:endpoint_url, :subscriptions],
          map_present: [:provider_type]
  end
  module Tailscale
    include TailscaleWebhook
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
