# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_tailnet_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleTailnetSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_tailnet_settings,
      attributes_class: Tailscale::Types::TailnetSettingsAttributes,
          outputs: { id: :id },
          map_present: [:acls_externally_managed_on, :acls_external_link, :devices_approval_on, :devices_auto_updates_on, :devices_key_duration_days, :users_approval_on, :users_role_allowed_to_join_external_tailnet, :posture_identity_collection_on, :https_enabled, :network_flow_logging_on, :regional_routing_on]
  end
  module Tailscale
    include TailscaleTailnetSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
