# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class TailnetSettingsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute? :acls_externally_managed_on, T::Bool.optional
    attribute? :acls_external_link, T::String.optional
    attribute? :devices_approval_on, T::Bool.optional
    attribute? :devices_auto_updates_on, T::Bool.optional
    attribute? :devices_key_duration_days, T::Integer.optional
    attribute? :users_approval_on, T::Bool.optional
    attribute? :users_role_allowed_to_join_external_tailnet, T::String.optional
    attribute? :posture_identity_collection_on, T::Bool.optional
    attribute? :https_enabled, T::Bool.optional
    attribute? :network_flow_logging_on, T::Bool.optional
    attribute? :regional_routing_on, T::Bool.optional
  end
end
