# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_aws_external_id/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleAwsExternalId
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_aws_external_id,
      attributes_class: Tailscale::Types::AwsExternalIdAttributes,
          outputs: { id: :id, external_id: :external_id, tailscale_aws_account_id: :tailscale_aws_account_id }
  end
  module Tailscale
    include TailscaleAwsExternalId
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
