#!/usr/bin/env ruby
# frozen_string_literal: true
#
# tools/regen.rb — bootstrap regenerator for pangea-tailscale
#
# Reads ../tailscale-terraform-resources (TOML catalog, source of truth) and
# emits typed Ruby gem files matching the shape pangea-forge produces.
#
# This is a temporary bootstrap — once iac-forge / pangea-forge has been
# healed past the synthesizer-family refactor, this script is replaced by:
#
#   iac-forge generate \
#     --backend pangea \
#     --resources ../tailscale-terraform-resources/resources \
#     --provider ../tailscale-terraform-resources/provider.toml \
#     --output ./
#
# At that point the generated output should match this script's output
# (modulo formatting); diff before deleting.
#
# Usage: ruby tools/regen.rb [path-to-catalog]

require 'tomlrb'
require 'fileutils'
require 'pathname'

CATALOG = ARGV[0] || File.expand_path('../tailscale-terraform-resources', __dir__ + '/..')
GEM_ROOT = File.expand_path('..', __dir__)

PROVIDER = 'tailscale'
PROVIDER_RB = 'Tailscale'  # Ruby-side module name

# ── Helpers ────────────────────────────────────────────────────────────────

def to_module_name(resource_name)
  # tailscale_oauth_client → TailscaleOauthClient
  resource_name.split('_').map(&:capitalize).join
end

def to_attr_class_name(resource_name)
  # tailscale_oauth_client → OauthClientAttributes  (provider prefix stripped)
  inner = resource_name.sub(/^#{PROVIDER}_/, '')
  inner.split('_').map(&:capitalize).join + 'Attributes'
end

def ruby_type_for(field)
  case field['type']
  when 'String' then 'T::String'
  when 'Boolean' then 'T::Bool'
  when 'Number' then 'T::Integer'
  when 'List' then 'T::Array.of(T::String)'
  when 'Map' then 'T::Hash'
  else 'T::String'  # fallback
  end
end

# Sample value used in synthesis tests — must satisfy ruby_type_for
def sample_value_for(field)
  case field['type']
  when 'Boolean' then 'true'
  when 'Number'  then '1'
  when 'List'    then "['test-value']"
  when 'Map'     then "{ 'k' => 'v' }"
  else "'test-value'"
  end
end

def emit(path, content)
  full = File.join(GEM_ROOT, path)
  FileUtils.mkdir_p(File.dirname(full))
  File.write(full, content)
  puts "  emit #{path}"
end

# ── Load all resources from the catalog ────────────────────────────────────

resource_files = Dir.glob(File.join(CATALOG, 'resources/**/*.toml')).sort
provider_toml = Tomlrb.load_file(File.join(CATALOG, 'provider.toml'))

resources = resource_files.map do |path|
  data = Tomlrb.load_file(path)
  data
end

puts "regen: loaded #{resources.size} resources from #{CATALOG}"

# ── lib/pangea/resources/<resource>/types.rb (one per resource) ───────────

resources.each do |r|
  name = r['resource']['name']
  fields = r['fields'] || {}
  cls = to_attr_class_name(name)

  required = fields.select { |_, f| f['required'] && !f['computed'] }
  optional = fields.select { |_, f| !f['required'] && !f['computed'] }

  attr_lines = []
  required.each do |fname, f|
    attr_lines << "    attribute :#{fname}, #{ruby_type_for(f)}"
  end
  optional.each do |fname, f|
    attr_lines << "    attribute? :#{fname}, #{ruby_type_for(f)}.optional"
  end

  content = <<~RUBY
    # frozen_string_literal: true
    # Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

    require 'pangea/resources/base_attributes'

    module Pangea::Resources::Tailscale::Types
      include Dry.Types()

      class #{cls} < Pangea::Resources::BaseAttributes
        T = Pangea::Resources::Tailscale::Types

    #{attr_lines.join("\n")}
      end
    end
  RUBY

  emit "lib/pangea/resources/#{name}/types.rb", content
end

# ── lib/pangea/resources/<resource>/resource.rb (one per resource) ────────

resources.each do |r|
  name = r['resource']['name']
  fields = r['fields'] || {}
  mod = to_module_name(name)
  cls = to_attr_class_name(name)

  required_keys = fields.select { |_, f| f['required'] && !f['computed'] }.keys
  optional_keys = fields.select { |_, f| !f['required'] && !f['computed'] }.keys
  computed_keys = fields.select { |_, f| f['computed'] }.keys

  outputs = ([:id] + computed_keys.map(&:to_sym)).uniq
  outputs_hash = outputs.map { |k| "#{k}: :#{k}" }.join(', ')

  map_required = required_keys.map { |k| ":#{k}" }.join(', ')
  map_optional = optional_keys.map { |k| ":#{k}" }.join(', ')

  define_args = ["attributes_class: Tailscale::Types::#{cls}"]
  define_args << "outputs: { #{outputs_hash} }"
  define_args << "map: [#{map_required}]" unless required_keys.empty?
  define_args << "map_present: [#{map_optional}]" unless optional_keys.empty?

  content = <<~RUBY
    # frozen_string_literal: true
    # Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

    require 'pangea/resources/base'
    require 'pangea/resources/reference'
    require 'pangea/resources/#{name}/types'
    require 'pangea/resource_registry'

    module Pangea::Resources
      module #{mod}
        include Pangea::Resources::ResourceBuilder

        define_resource :#{name},
          #{define_args.join(",\n          ")}
      end
      module Tailscale
        include #{mod}
      end
    end
    Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
  RUBY

  emit "lib/pangea/resources/#{name}/resource.rb", content
end

# ── lib/pangea/resources/tailscale.rb (aggregator) ─────────────────────────

mods = resources.map { |r| to_module_name(r['resource']['name']) }.sort
content = <<~RUBY
  # frozen_string_literal: true
  # Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

  module Pangea
    module Resources
      module Tailscale
  #{mods.map { |m| "      include #{m}" }.join("\n")}
      end
    end
  end
RUBY
emit 'lib/pangea/resources/tailscale.rb', content

# ── lib/pangea/types/tailscale_types.rb (provider-wide types) ─────────────

content = <<~RUBY
  # frozen_string_literal: true

  require 'dry-types'
  require 'pangea/resources/types'

  module Pangea
    module Resources
      module Tailscale
        # Provider-specific Dry::Types for Tailscale resources.
        # Per-resource types.rb files reference these via
        # `T = Pangea::Resources::Tailscale::Types`.
        module Types
          include Dry.Types()

          T = ::Pangea::Resources::Types

          # Logstream destination types
          LogstreamDestinationType = T::String.constrained(
            included_in: %w[axiom cribl datadog elastic gcs panther splunk s3]
          )

          # Logstream log types
          LogstreamLogType = T::String.constrained(
            included_in: %w[configuration network]
          )

          # Logstream compression formats
          LogstreamCompressionFormat = T::String.constrained(
            included_in: %w[none zstd gzip]
          )

          # S3 authentication types
          S3AuthenticationType = T::String.constrained(
            included_in: %w[rolearn accesskey]
          )

          # Posture provider types
          PostureProvider = T::String.constrained(
            included_in: %w[falcon fleet huntress intune jamfpro kandji kolide sentinelone]
          )

          # Webhook provider types
          WebhookProviderType = T::String.constrained(
            included_in: %w[slack mattermost googlechat discord]
          )

          # Tailnet-key recreate-if-invalid policy
          TailnetKeyRecreatePolicy = T::String.constrained(
            included_in: %w[always never]
          )
        end
      end
    end
  end
RUBY
emit 'lib/pangea/types/tailscale_types.rb', content

# ── lib/pangea-tailscale.rb (top-level gem entry) ─────────────────────────

names = resources.map { |r| r['resource']['name'] }.sort
requires = names.map { |n| "require_relative 'pangea/resources/#{n}/resource'" }

content = <<~RUBY
  # frozen_string_literal: true
  # Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

  require 'pangea-core'
  require 'terraform-synthesizer'

  module Pangea; module Resources; module Tailscale; module Types; end; end; end; end

  # Tailscale resources
  #{requires.join("\n")}

  # Tailscale module aggregator
  require_relative 'pangea/resources/tailscale'
RUBY
emit 'lib/pangea-tailscale.rb', content

# ── spec/resources/<resource>_spec.rb (basic synthesis test) ──────────────

resources.each do |r|
  name = r['resource']['name']
  mod = to_module_name(name)
  fields = r['fields'] || {}
  required_keys = fields.select { |_, f| f['required'] && !f['computed'] }.keys
  optional_keys = fields.select { |_, f| !f['required'] && !f['computed'] }.keys
  computed_keys = fields.select { |_, f| f['computed'] }.keys

  # When a resource has no required fields, the synthesizer emits nothing
  # for an empty input hash. Fill in one optional attribute so synthesis
  # actually produces a resource block we can validate.
  test_keys = required_keys.empty? ? optional_keys.first(1) : required_keys
  required_attrs_hash = test_keys.map { |k|
    "#{k}: #{sample_value_for(fields[k])}"
  }.join(', ')
  required_syms = required_keys.map { |k| ":#{k}" }.join(', ')

  output_lines = [':id'].concat(computed_keys.map { |c| ":#{c}" }).uniq.map do |sym|
    name_only = sym.sub(/^:/, '')
    "        expect(ref.#{name_only}).to eq(\"\\${#{name}.test.#{name_only}}\")"
  end

  # All-computed resources (no required, no optional) can't be exercised
  # by the synthesizer — calling with `{}` emits nothing, and there's no
  # writable field to populate. This is a known limitation in the Pangea
  # ResourceBuilder DSL (matches the gap in pangea-datadog). Mark such
  # synthesis tests pending so the suite stays green.
  all_computed = required_keys.empty? && optional_keys.empty?

  synth_test_body = if all_computed
    <<~PEND
              pending('all-computed resource — Pangea ResourceBuilder cannot exercise without writable fields')
              raise 'unreachable'
    PEND
  else
    <<~ASSERT
              synth = create_synthesizer
              synth.extend(described_class)
              synth.#{name}('test', required_attrs)
              result = normalize_synthesis(synth.synthesis)

              validate_terraform_structure(result, :resource)
              config = validate_resource_structure(result, '#{name}', 'test')
              #{required_keys.empty? ? "# no required attributes" : "validate_required_attributes(config, [#{required_syms}])"}
    ASSERT
  end

  ref_test_body = if all_computed
    <<~PEND
              pending('all-computed resource — Pangea ResourceBuilder cannot exercise without writable fields')
              raise 'unreachable'
    PEND
  else
    <<~ASSERT
              synth = create_synthesizer
              synth.extend(described_class)
              ref = synth.#{name}('test', required_attrs)

              expect(ref).to be_a(Pangea::Resources::ResourceReference)
              expect(ref.resource_type).to eq(:#{name})
    ASSERT
  end

  content = <<~RUBY
    # frozen_string_literal: true
    # Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

    require 'spec_helper'

    RSpec.describe Pangea::Resources::#{mod} do
      include Pangea::Testing::SynthesisTestHelpers

      let(:required_attrs) { { #{required_attrs_hash} } }

      describe ':#{name}' do
        context 'with required attributes only' do
          it 'synthesizes valid Terraform JSON' do
    #{synth_test_body.chomp}
          end

          it 'returns a ResourceReference' do
    #{ref_test_body.chomp}
          end
        end
      end
    end
  RUBY

  emit "spec/resources/#{name}_spec.rb", content
end

puts "regen: done — wrote #{resources.size * 3 + 3} files"
