# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_dns_search_paths/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDnsSearchPaths
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_dns_search_paths,
      attributes_class: Tailscale::Types::DnsSearchPathsAttributes,
          outputs: { id: :id },
          map: [:search_paths]
  end
  module Tailscale
    include TailscaleDnsSearchPaths
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
