# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_device_subnet_routes/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDeviceSubnetRoutes
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_device_subnet_routes,
      attributes_class: Tailscale::Types::DeviceSubnetRoutesAttributes,
          outputs: { id: :id },
          map: [:device_id, :routes]
  end
  module Tailscale
    include TailscaleDeviceSubnetRoutes
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
