# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_device_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleDeviceKey
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_device_key,
      attributes_class: Tailscale::Types::DeviceKeyAttributes,
          outputs: { id: :id },
          map: [:device_id],
          map_present: [:key_expiry_disabled]
  end
  module Tailscale
    include TailscaleDeviceKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
