# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'spec_helper'

RSpec.describe Pangea::Resources::TailscaleAwsExternalId do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {  } }

  describe ':tailscale_aws_external_id' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
pending('all-computed resource — Pangea ResourceBuilder cannot exercise without writable fields')
raise 'unreachable'
      end

      it 'returns a ResourceReference' do
pending('all-computed resource — Pangea ResourceBuilder cannot exercise without writable fields')
raise 'unreachable'
      end
    end
  end
end
