# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'spec_helper'

RSpec.describe Pangea::Resources::TailscaleAcl do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { acl: 'test-value' } }

  describe ':tailscale_acl' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
synth = create_synthesizer
synth.extend(described_class)
synth.tailscale_acl('test', required_attrs)
result = normalize_synthesis(synth.synthesis)

validate_terraform_structure(result, :resource)
config = validate_resource_structure(result, 'tailscale_acl', 'test')
validate_required_attributes(config, [:acl])
      end

      it 'returns a ResourceReference' do
synth = create_synthesizer
synth.extend(described_class)
ref = synth.tailscale_acl('test', required_attrs)

expect(ref).to be_a(Pangea::Resources::ResourceReference)
expect(ref.resource_type).to eq(:tailscale_acl)
      end
    end
  end
end
