# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'spec_helper'

RSpec.describe Pangea::Resources::TailscaleLogstreamConfiguration do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { log_type: 'test-value', destination_type: 'test-value' } }

  describe ':tailscale_logstream_configuration' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
synth = create_synthesizer
synth.extend(described_class)
synth.tailscale_logstream_configuration('test', required_attrs)
result = normalize_synthesis(synth.synthesis)

validate_terraform_structure(result, :resource)
config = validate_resource_structure(result, 'tailscale_logstream_configuration', 'test')
validate_required_attributes(config, [:log_type, :destination_type])
      end

      it 'returns a ResourceReference' do
synth = create_synthesizer
synth.extend(described_class)
ref = synth.tailscale_logstream_configuration('test', required_attrs)

expect(ref).to be_a(Pangea::Resources::ResourceReference)
expect(ref.resource_type).to eq(:tailscale_logstream_configuration)
      end
    end
  end
end
