# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'spec_helper'

RSpec.describe Pangea::Resources::TailscaleTailnetSettings do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { acls_externally_managed_on: true } }

  describe ':tailscale_tailnet_settings' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
synth = create_synthesizer
synth.extend(described_class)
synth.tailscale_tailnet_settings('test', required_attrs)
result = normalize_synthesis(synth.synthesis)

validate_terraform_structure(result, :resource)
config = validate_resource_structure(result, 'tailscale_tailnet_settings', 'test')
# no required attributes
      end

      it 'returns a ResourceReference' do
synth = create_synthesizer
synth.extend(described_class)
ref = synth.tailscale_tailnet_settings('test', required_attrs)

expect(ref).to be_a(Pangea::Resources::ResourceReference)
expect(ref.resource_type).to eq(:tailscale_tailnet_settings)
      end
    end
  end
end
