# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/tailscale_logstream_configuration/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module TailscaleLogstreamConfiguration
    include Pangea::Resources::ResourceBuilder

    define_resource :tailscale_logstream_configuration,
      attributes_class: Tailscale::Types::LogstreamConfigurationAttributes,
          outputs: { id: :id },
          map: [:log_type, :destination_type],
          map_present: [:compression_format, :url, :token, :user, :upload_period_minutes, :s3_bucket, :s3_region, :s3_authentication_type, :s3_access_key_id, :s3_secret_access_key, :s3_role_arn, :s3_external_id, :s3_key_prefix, :gcs_bucket, :gcs_credentials, :gcs_key_prefix, :gcs_scopes]
  end
  module Tailscale
    include TailscaleLogstreamConfiguration
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Tailscale)
