# frozen_string_literal: true
# Code generated by pangea-tailscale tools/regen.rb. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Tailscale::Types
  include Dry.Types()

  class LogstreamConfigurationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Tailscale::Types

    attribute :log_type, T::String
    attribute :destination_type, T::String
    attribute? :compression_format, T::String.optional
    attribute? :url, T::String.optional
    attribute? :token, T::String.optional
    attribute? :user, T::String.optional
    attribute? :upload_period_minutes, T::Integer.optional
    attribute? :s3_bucket, T::String.optional
    attribute? :s3_region, T::String.optional
    attribute? :s3_authentication_type, T::String.optional
    attribute? :s3_access_key_id, T::String.optional
    attribute? :s3_secret_access_key, T::String.optional
    attribute? :s3_role_arn, T::String.optional
    attribute? :s3_external_id, T::String.optional
    attribute? :s3_key_prefix, T::String.optional
    attribute? :gcs_bucket, T::String.optional
    attribute? :gcs_credentials, T::String.optional
    attribute? :gcs_key_prefix, T::String.optional
    attribute? :gcs_scopes, T::Array.of(T::String).optional
  end
end
